"""add request id to approvals

Revision ID: ca24283b2403
Revises: 9912c2fdf168
Create Date: 2026-09-04 17:55:50.850322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca24283b2403'
down_revision: Union[str, Sequence[str], None] = '9912c2fdf168'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approvals', sa.Column('request_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('approvals', 'request_id')
    # ### end Alembic commands ###
